name: Test
on: [push]

jobs:
  build:
    strategy:
      matrix:
        php: ['7.1', '7.2', '7.3']
      fail-fast: false
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Install PHP
      uses: shivammathur/setup-php@1.3.7
      with:
        php-version: ${{ matrix.php }}

    - name: Debugging
      run: |
        php --version
        php -m
        composer --version

    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-suggest

    - name: Run tests
      run: composer run test
